export const categories = [
    {
        id: 1,
        name: 'Cabai',
        image: require('../assets/images/cabai.jpeg'),
    },
    {
        id: 2,
        name: 'Terong',
        image: require('../assets/images/terong.jpeg'),
    },
    {
        id: 3,
        name: 'Jagung',
        image: require('../assets/images/jagung.jpeg'),
    },
    {
        id: 4,
        name: 'Tomat',
        image: require('../assets/images/tomat.jpeg'),
    },
    {
        id: 5,
        name: 'Kacang',
        image: require('../assets/images/kacang.jpeg'),
    },
    {
        id: 6,
        name: 'Ubi',
        image: require('../assets/images/ubi.jpeg'),
    },
];

export const featured = [
    {
        id: 1,
        title: 'Cabai Rawit',
        description: 'Cabai segar fresh baru di panen',
        petani: [
            {
                id: 1,
                name: 'Warung Cabe Jos',
                lng: -7.73358850432051,
                lat: 110.29372334914707,
                address: 'Kurahan Lor, Margodadi, Seyegan, Sleman Regency, Special Region of Yogyakarta 55561',
                stars: 4,
                review: '1.4k',
                category: 'Sayur Segar',
                panen: [
                    { id: 1, name: 'Cabai rawit merah', price: 60000 },
                    { id: 2, name: 'Cabai merah besar', price: 60000 },
                    { id: 3, name: 'Cabai merah keriting', price: 43000 },
                    { id: 4, name: 'Cabai rawit hijau', price: 50000 },
                    { id: 5, name: 'Cabai hijau besar', price: 35000 },
                ],
            },
            {
                id: 2,
                name: 'Farm Chili',
                lng: -7.667058697801447,
                lat: 110.3183138119975,
                address: 'Gentan, Margomulyo, Kec. Seyegan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55561',
                stars: 5,
                review: '3.9k',
                category: 'Cabai segar',
                panen: [
                    { id: 1, name: 'Cabai rawit merah', price: 55000 },
                    { id: 2, name: 'Cabai merah besar', price: 56000 },
                    { id: 3, name: 'Cabai merah keriting', price: 46000 },
                    { id: 4, name: 'Cabai rawit hijau', price: 53000 },
                    { id: 5, name: 'Cabai hijau besar', price: 33000 },
                ],
            },
        ],
    },
    {
        id: 2,
        title: 'Terong',
        description: 'Terong segar dan fresh baru di panen',
        petani: [
            {
                id: 1,
                name: 'Mitra Terong',
                lng: -7.702427774992702,
                lat: 110.34878797495418,
                address: 'Pasar Sleman, Jl. Sersan Kusdiyo No.18, Kalah Ijo 1, Triharjo, Kec. Sleman, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55514',
                stars: 5,
                review: '4.7k',
                category: 'Sayur Segar',
                panen: [
                    { id: 1, name: 'Terong ungu', price: 10000 },
                    { id: 2, name: 'Terong hijau', price: 12000 },
                    { id: 3, name: 'Terong mini', price: 15000 },
                ],
            },
            {
                id: 2,
                name: 'Depot Terong',
                lng: -7.7310036434107285,
                lat: 110.32611141365071,
                address: 'Cabakan, Sumberadi, Mlati, Sleman Regency, Special Region of Yogyakarta 55288',
                stars: 4,
                review: '1.2k',
                category: 'Terong segar',
                panen: [
                    { id: 1, name: 'Terong ungu', price: 11000 },
                    { id: 2, name: 'Terong hijau', price: 11000 },
                    { id: 3, name: 'Terong mini', price: 13000 },
                ],
            },
        ],
    },
    {
        id: 3,
        title: 'Jagung',
        description: 'Jagung manis fresh baru di panen',
        petani: [
            {
                id: 1,
                name: 'Jagung Manisku',
                lng: -7.70216213495403, 
                lat: 110.39219748176258,
                address: 'Jl. Rejodani, Tambak Rejo, Sariharjo, Kec. Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581',
                stars: 5,
                review: '2.4k',
                category: 'Jagung manis',
                panen: [
                    { id: 1, name: 'Jagung manis', price: 10000 },
                    { id: 2, name: 'Jagung pipil kering', price: 8000 },
                ],
            },
            {
                id: 2,
                name: 'Kebun Djagung',
                lng: -7.727106249354632, 
                lat: 110.3325590137853,
                address: 'Bedingin, Sumberadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55288',
                stars: 5,
                review: '5.0k',
                category: 'Terong segar',
                panen: [
                    { id: 1, name: 'Jagung manis', price: 9000 },
                    { id: 2, name: 'Jagung pipil kering', price: 7000 },
                ],
            },
        ],
    },
    {
        id: 4,
        title: 'Tomat',
        description: 'Tomat segar dan fresh baru di panen',
        petani: [
            {
                id: 1,
                name: 'Tomatkura',
                lng: -7.723593108851226, 
                lat: 110.28803705990005,
                address: 'Margokaton, Seyegan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581',
                stars: 3,
                review: '1.0k',
                category: 'Tomat segar',
                panen: [
                    { id: 1, name: 'Tomat Buah', price: 12000 },
                    { id: 2, name: 'Tomat Sayur', price: 10000 },
                    { id: 3, name: 'Tomat Cherry', price: 35000 },
                ],
            },
            {
                id: 2,
                name: 'Tomat Pak Asep',
                lng: -7.6621599089287455,  
                lat: 110.3155381059916,
                address: 'Mororejo, Kec. Tempel, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55288',
                stars: 4,
                review: '3.8k',
                category: 'Tomat organik',
                panen: [
                    { id: 1, name: 'Tomat Buah', price: 15000 },
                    { id: 2, name: 'Tomat Sayur', price: 13000 },
                    { id: 3, name: 'Tomat Cherry', price: 36000 },
                ],
            },
        ],
    },
    {
        id: 5,
        title: 'Kacang',
        description: 'Kacang tanah baru di panen',
        petani: [
            {
                id: 1,
                name: 'Kacang Tanah Pak Hartanto',
                lng: -7.667262839232641,  
                lat: 110.34502145997888,
                address: 'Kolisasih, Trimulyo, Sleman, Sleman Regency, Special Region of Yogyakarta 55513',
                stars: 4,
                review: '2.8k',
                category: 'Kacang tanah fresh',
                panen: [
                    { id: 1, name: 'Kacang tanah mentah', price: 18000 },
                    { id: 2, name: 'Kacang tanah kupas', price: 30000 },
                ],
            },
            {
                id: 2,
                name: 'Warung Kacang Pak Sunu',
                lng: -7.706271100820776, 
                lat: 110.33224547251243,
                address: 'Jumeneng cilik No.001/003, Jumenang Cilik, Margomulyo, Kec. Seyegan, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55561',
                stars: 5,
                review: '3.1k',
                category: 'Kacang tanah fresh',
                panen: [
                    { id: 1, name: 'Kacang tanah mentah', price: 19000 },
                    { id: 2, name: 'Kacang tanah kupas', price: 29000 },
                ],
            },
        ],
    },
    {
        id: 6,
        title: 'Ubi',
        description: 'Ubi manis dan segar baru di panen',
        petani: [
            {
                id: 1,
                name: 'Toko Ubi manis Pak Haki ',
                lng: -7.657261728290017, 
                lat: 110.335661130189,
                address: 'Jl. Magelang No.Km 17, RW.5, Jlegingan, Margorejo, Kec. Tempel, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55552',
                stars: 5,
                review: '3.1k',
                category: 'Ubi manis',
                panen: [
                    { id: 1, name: 'Ubi jalar ungu', price: 15000 },
                    { id: 2, name: 'Ubi jalar kuning', price: 13000 },
                    { id: 3, name: 'Ubi jalar putih', price: 12000 },
                ],
            },
            {
                id: 2,
                name: 'Warung ubi Pak Juyo',
                lng: -7.698541610919899,  
                lat: 110.3689205615527,
                address: 'Dukuh, Pandowoharjo, Sleman, Sleman Regency, Special Region of Yogyakarta 56433',
                stars: 5,
                review: '2.8k',
                category: 'Ubi manis',
                panen: [
                    { id: 1, name: 'Ubi jalar ungu', price: 17000 },
                    { id: 2, name: 'Ubi jalar kuning', price: 14000 },
                    { id: 3, name: 'Ubi jalar putih', price: 11000 },
                ],
            },
        ],
    },
];
